'use client';
import { useState, type Dispatch, type FormEvent, type SetStateAction } from 'react';
import { ArrowRight, ClipboardList, Download, Mail, MessageCircle, X } from 'lucide-react';
import { products, type Lang, type QuoteItem } from '@/lib/catalog';
import { itemText, mailLink, chatLink } from '@/lib/inquiry';
import { colourLabel } from '@/lib/colours';
type Inquiry={name:string;company:string;email:string;phone:string;message:string;items:QuoteItem[]};

export default function QuoteForm({lang,items,setItems,whatsapp,salesEmail}:{lang:Lang;items:QuoteItem[];setItems:Dispatch<SetStateAction<QuoteItem[]>>;whatsapp:string;salesEmail:string}) {
  const [inquiry,setInquiry]=useState<Inquiry|null>(null);
  const t=(id:string,en:string)=>lang==='id'?id:en;
  const inquiryText=()=>inquiry?[
    t('Halo BOSS BAHAN PVC, mohon penawaran untuk kebutuhan berikut.','Hello BOSS BAHAN PVC, please provide a quotation for the following requirements.'),'',
    t('Nama: ','Name: ')+inquiry.name,t('Perusahaan: ','Company: ')+inquiry.company,'Email: '+inquiry.email,t('Telepon: ','Phone: ')+(inquiry.phone||'—'),'',
    ...inquiry.items.map(i=>itemText(i,lang)),'',inquiry.message,'',t('Mohon informasi harga, ketersediaan, dan pengiriman. Terima kasih.','Please advise pricing, availability and delivery options. Thank you.'),
  ].join('\n'):'';
  const download=()=>{
    const url=URL.createObjectURL(new Blob([inquiryText()],{type:'text/plain;charset=utf-8'}));
    const a=document.createElement('a');a.href=url;a.download='BOSS-BAHAN-PVC-Inquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  function prepare(e:FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const data=new FormData(e.currentTarget);
    setInquiry({name:String(data.get('name')||'').trim(),company:String(data.get('company')||'').trim(),email:String(data.get('email')||'').trim(),phone:String(data.get('phone')||'').trim(),message:String(data.get('message')||'').trim(),items:[...items]});
  }
  return <div className="quote-form">
    {inquiry?<div aria-live="polite"><Mail size={35} className="text-[#a27b42]"/><h3 className="text-2xl font-bold mt-4">{t('Permintaan siap dikirim.','Your inquiry is ready.')}</h3><p className="text-sm text-[#727e70] leading-6 mt-3">{t('Periksa ringkasan Anda, lalu kirim melalui WhatsApp atau buka draf email untuk tim kami.','Review your summary, then send it via WhatsApp or open an email draft for our team.')}</p><pre className="p-4 bg-[#f3f5f1] rounded-md text-xs leading-6 font-sans whitespace-pre-wrap max-h-64 overflow-y-auto mt-5">{inquiryText()}</pre><div className="flex flex-wrap gap-3 mt-5">{salesEmail&&<a className="btn btn-dark" href={mailLink(salesEmail,inquiryText())}><Mail size={17}/>{t('Buka Draf Email','Open Email Draft')}</a>}{whatsapp&&<a className="btn btn-outline" target="_blank" rel="noopener noreferrer" href={chatLink(whatsapp,inquiryText())}><MessageCircle size={17}/>WhatsApp</a>}<button className="btn btn-outline" onClick={download} aria-label={t('Unduh ringkasan permintaan','Download inquiry summary')}><Download size={17}/>{t('Simpan','Save')}</button></div><p className="text-xs text-[#7f897d] mt-4 leading-5">{salesEmail?t('Tujuan email: ','Email to: ')+salesEmail:t('Alamat email penawaran sedang disiapkan.','The quotation email address is being prepared.')}<br/>{t('Permintaan belum dikirim. Silakan kirim dari aplikasi email atau WhatsApp Anda.','Your inquiry has not been sent. Please send it from your email or WhatsApp application.')}</p><button type="button" className="text-sm underline mt-5 text-[#6f7a6c]" onClick={()=>setInquiry(null)}>{t('Ubah Permintaan','Edit Inquiry')}</button></div>:null}
    <form className={inquiry?'hidden':''} onSubmit={prepare}>
      <div className="flex items-center justify-between gap-4"><h3 className="text-xl font-bold tracking-tight">{t('Permintaan Penawaran','Request a Quotation')}</h3><ClipboardList size={22} className="text-[#9c8057]"/></div><p className="text-xs text-[#899083] mt-2 mb-6">{t('Lengkapi informasi berikut. Kolom bertanda * wajib diisi.','Please complete the details below. Fields marked * are required.')}</p>
      <div className="space-y-3 mb-5">{items.map((item,i)=>{const p=products.find(p=>p.id===item.productId)!;const variant=p.variants.find(v=>v.id===item.variantId)!;return <div className="quote-line" key={item.productId+'-'+item.variantId+'-'+i}><img src={p.images[0]} alt="" width="45" height="45"/><div className="min-w-0 flex-1"><p className="text-xs font-bold">{p.name[lang]}</p><p className="text-[11px] text-[#7e8777] mt-1">{variant.label}{item.color?' · '+colourLabel(item.color,lang):''}</p><div className="flex gap-2 mt-2"><label className="flex gap-2 items-center text-[11px] text-[#74806f]">{t('Jumlah','Quantity')}<input className="w-16 border border-[#d9dfd5] rounded px-2 py-1 bg-white text-[#374232]" type="number" min="1" max="99999" step="1" required aria-label={t('Jumlah: ','Quantity: ')+p.name[lang]} value={item.quantity} onChange={e=>setItems(current=>current.map((v,index)=>index===i?{...v,quantity:e.target.valueAsNumber||1}:v))}/></label><select className="border border-[#d9dfd5] rounded px-1 py-1 bg-white text-[11px] text-[#374232]" aria-label={t('Satuan: ','Unit: ')+p.name[lang]} value={item.unit} onChange={e=>setItems(current=>current.map((v,index)=>index===i?{...v,unit:e.target.value as QuoteItem['unit']}:v))}><option value="roll">Roll</option><option value="meter">{t('Meter','Metre')}</option><option value="piece">{t('Lembar','Piece')}</option></select></div></div><button type="button" className="p-2" aria-label={t('Hapus ','Remove ')+p.name[lang]} onClick={()=>setItems(current=>current.filter((_,index)=>index!==i))}><X size={15}/></button></div>})}</div>
      <label className="field mb-5">{t('Produk yang diminati','Products of interest')}<select value="" onChange={e=>{const p=products.find(p=>p.id===e.target.value);if(p&&!items.some(i=>i.productId===p.id))setItems(current=>[...current,{productId:p.id,variantId:p.variants[0].id,color:'',quantity:1,unit:p.unit==='piece'?'piece':'roll'}])}}><option value="">{t('+ Pilih produk untuk ditanyakan','+ Select a product to inquire about')}</option>{products.map(p=><option key={p.id} value={p.id} disabled={items.some(i=>i.productId===p.id)}>{p.name[lang]}</option>)}</select></label>
      <div className="grid sm:grid-cols-2 gap-4"><label className="field">{t('Nama lengkap','Full name')} *<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder={t('Nama Anda','Your name')}/></label><label className="field">{t('Nama perusahaan / usaha','Company / business name')} *<input name="company" autoComplete="organization" required minLength={2} maxLength={150} placeholder={t('Nama usaha Anda','Your business name')}/></label><label className="field">Email *<input name="email" type="email" autoComplete="email" required maxLength={200} placeholder={t('nama@perusahaan.com','name@company.com')}/></label><label className="field">{t('Nomor WhatsApp / telepon','WhatsApp / phone number')}<input name="phone" type="tel" autoComplete="tel" maxLength={30} pattern="[+0-9 ().\-]{6,30}" placeholder="+62 ..."/></label></div>
      <label className="field mt-4">{t('Detail kebutuhan & tujuan pengiriman','Requirements & delivery destination')} {items.length===0?'*':''}<textarea name="message" required={items.length===0} minLength={items.length===0?10:undefined} maxLength={3000} placeholder={t('Jenis bahan, ukuran / ketebalan, jumlah kebutuhan, dan kota tujuan pengiriman...','Material, dimensions / thickness, quantity and delivery city...')}/></label>
      <button type="submit" className="btn btn-gold w-full mt-5">{t('Siapkan Permintaan Penawaran','Prepare Quote Inquiry')}<ArrowRight size={17}/></button>
      <p className="mt-4 text-[11px] text-[#8a9484] leading-5 text-center">{t('Tinjau permintaan sebelum mengirim melalui email atau WhatsApp.','Review your inquiry before sending by email or WhatsApp.')}</p>
    </form>
  </div>;
}
